[package]
name = "storyteller"
version = "0.3.1"
edition = "2018"

authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Library focused on supporting user oriented output while supporting multiple output types (e.g. json, a progressbar, etc.)"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/foresterre/storyteller"

[package.metadata]
msrv = "1.38"

exclude = ["/.github", "docs/sketches/*.png"]

[dependencies]
crossbeam-channel = "0.5"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
indicatif = "0.16.2"