[licenses]
unlicensed = "deny"
copyleft = "deny"
confidence-threshold = 0.925
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-DFS-2016",
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = []
