name: "ci-fmt"
on:
  pull_request:
  push:
    branches:
      - master
      - main
      - staging # for Bors
      - trying # for Bors
jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-18.04
    steps:
      - name: checkout_repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: install_rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: install_rustfmt
        run: rustup component add rustfmt

      - name: check_formatting
        run: |
          cargo fmt -- --check
